### ISSUE TITLE
本地运行出现各种报错 啥情况啊  能不能

### ISSUE THREAD

**Issue by abshawn** [buzheng/start-project-easyui-springmvc-mybatis#2]
附件是该项目报错的日志，详见附件 
还真没看明白了什么地方有问题

**Comment by abshawn** [comment]
[Uploading debug.txt…]()

[Uploading info.txt…]()

**Comment by buzheng** [comment]
没搞懂附件在哪里？ 发我邮箱吧。 zhjiun@gmail.com

**Comment by abshawn** [comment]
已发附件到你邮箱  谢谢
